-- Conquest of Azeroth class support for the Gear Advisor.
-- CoA characters use classes this addon has no stat weights for, so they fall back to the
-- generic "CUSTOM" weights. For a known CoA class, replace those generic builds with the
-- class's real specs so the advisor scores gear for Infinite/Time/Artificer (and so on)
-- instead of three identical "Custom Spec" entries.
--
-- Class/spec data copied from Kui_Nameplates\CoAClassSpecData.lua, which is generated by
-- coa-db/tools/gen_coa_class_spec_lua.py from coa-db/data/class_spec_meta.json. Keyed by the
-- in-game class token (2nd return of UnitClass). Weights use neutral stat names.

local ZGV = ZygorGuidesViewer
local ItemScore = ZGV.ItemScore

local CoAClassSpec = {
  ["BARBARIAN"] = { name="Barbarian", classId=12, specs={
    { name="Headhunting", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Brutality", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Ancestry", roles={"MELEE","SUPPORT"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
  }},
  ["WITCHDOCTOR"] = { name="Witch Doctor", classId=13, specs={
    { name="Shadowhunting", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Voodoo", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Brewing", roles={"HEALER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Intellect=0.55 } },
  }},
  ["DEMONHUNTER"] = { name="Felsworn", classId=14, specs={
    { name="Slayer", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Infernal", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Tyrant", roles={"TANK"}, primaryStat="Agility", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Agility=0.4 } },
  }},
  ["WITCHHUNTER"] = { name="Witch Hunter", classId=15, specs={
    { name="Boltslinger", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Darkness", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Inquisition", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Black Knight", roles={"TANK"}, primaryStat="Agility", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Agility=0.4 } },
  }},
  ["STORMBRINGER"] = { name="Stormbringer", classId=16, specs={
    { name="Maelstrom", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Lightning", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Wind", roles={"CASTER","SUPPORT"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
  }},
  ["FLESHWARDEN"] = { name="Knight of Xoroth", classId=17, specs={
    { name="Hellfire", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Defiance", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
    { name="War", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
  }},
  ["GUARDIAN"] = { name="Guardian", classId=18, specs={
    { name="Gladiator", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Inspiration", roles={"MELEE","SUPPORT"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Vanguard", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
  }},
  ["MONK"] = { name="Templar", classId=19, specs={
    { name="Oathkeeper", roles={"TANK"}, primaryStat="Agility", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Agility=0.4 } },
    { name="Zealot", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Crusader", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
  }},
  ["SONOFARUGAL"] = { name="Bloodmage", classId=20, specs={
    { name="Fleshweaver", roles={"SUPPORT"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Sanguine", roles={"CASTER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Accursed", roles={"MELEE","CASTER"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Eternal", roles={"TANK"}, primaryStat="Agility", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Agility=0.4 } },
  }},
  ["RANGER"] = { name="Ranger", classId=21, specs={
    { name="Archery", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Farstrider", roles={"RANGED","SUPPORT"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Brigand", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
  }},
  ["CHRONOMANCER"] = { name="Chronomancer", classId=22, specs={
    { name="Infinite", roles={"CASTER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Time", roles={"HEALER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Intellect=0.55 } },
    { name="Artificer", roles={"RANGED"}, primaryStat="Spirit", weights={ Spirit=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
  }},
  ["NECROMANCER"] = { name="Necromancer", classId=23, specs={
    { name="Death", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Animation", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Rime", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
  }},
  ["PYROMANCER"] = { name="Pyromancer", classId=24, specs={
    { name="Incineration", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Flameweaving", roles={"HEALER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Intellect=0.55 } },
    { name="Draconic", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
  }},
  ["CULTIST"] = { name="Cultist", classId=25, specs={
    { name="Heretic", roles={"HEALER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Spirit=0.55 } },
    { name="Corruption", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Godblade", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Dreadnought", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
  }},
  ["STARCALLER"] = { name="Starcaller", classId=26, specs={
    { name="Sentinel", roles={"RANGED"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Warden", roles={"MELEE"}, primaryStat="Intellect", weights={ Intellect=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Moon Priest", roles={"HEALER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Spirit=0.55 } },
    { name="Moon Guard", roles={"TANK"}, primaryStat="Intellect", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Intellect=0.4 } },
  }},
  ["SUNCLERIC"] = { name="Sun Cleric", classId=27, specs={
    { name="Piety", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Valkyrie", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Seraphim", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
    { name="Blessings", roles={"HEALER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Spirit=0.55 } },
  }},
  ["TINKER"] = { name="Tinker", classId=28, specs={
    { name="Demolition", roles={"RANGED"}, primaryStat="Agility", weights={ Agility=1, RangedAttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5 } },
    { name="Mechanics", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Invention", roles={"HEALER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Spirit=0.55 } },
  }},
  ["PROPHET"] = { name="Venomancer", classId=29, specs={
    { name="Fortitude", roles={"TANK"}, primaryStat="Intellect", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Intellect=0.4 } },
    { name="Stalking", roles={"MELEE"}, primaryStat="Intellect", weights={ Intellect=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Rot", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Vizier", roles={"HEALER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, CritRating=0.5, HasteRating=0.5, Mp5=0.5, Spirit=0.55 } },
  }},
  ["REAPER"] = { name="Reaper", classId=30, specs={
    { name="Soul", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Harvest", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Domination", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
  }},
  ["WILDWALKER"] = { name="Primalist", classId=31, specs={
    { name="Grovekeeper", roles={"SUPPORT"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Wildwalker", roles={"MELEE"}, primaryStat="Strength", weights={ Strength=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Mountain King", roles={"TANK"}, primaryStat="Strength", weights={ Stamina=1, Armor=0.6, Dodge=0.55, Parry=0.55, Defense=0.6, Strength=0.4 } },
    { name="Geomancy", roles={"CASTER"}, primaryStat="Intellect", weights={ Intellect=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
  }},
  ["SPIRITMAGE"] = { name="Runemaster", classId=32, specs={
    { name="Engravement", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
    { name="Glyphic", roles={"CASTER"}, primaryStat="Spirit", weights={ Spirit=1, SpellPower=0.8, HitRating=0.7, CritRating=0.55, HasteRating=0.55 } },
    { name="Riftblade", roles={"MELEE"}, primaryStat="Agility", weights={ Agility=1, AttackPower=0.5, CritRating=0.55, HitRating=0.6, HasteRating=0.5, ArmorPenetration=0.5 } },
  }},
}

local CoAClassPrimaryStats = {
  ["BARBARIAN"] = { "Agility" },
  ["WITCHDOCTOR"] = { "Agility", "Intellect", "Spirit" },
  ["DEMONHUNTER"] = { "Agility", "Intellect", "Stamina" },
  ["WITCHHUNTER"] = { "Agility", "Intellect", "Stamina" },
  ["STORMBRINGER"] = { "Intellect" },
  ["FLESHWARDEN"] = { "Strength", "Intellect", "Stamina" },
  ["GUARDIAN"] = { "Strength", "Stamina" },
  ["MONK"] = { "Agility", "Stamina" },
  ["SONOFARUGAL"] = { "Spirit", "Stamina", "Agility" },
  ["RANGER"] = { "Agility" },
  ["CHRONOMANCER"] = { "Spirit" },
  ["NECROMANCER"] = { "Intellect" },
  ["PYROMANCER"] = { "Intellect", "Spirit" },
  ["CULTIST"] = { "Intellect", "Strength", "Stamina" },
  ["STARCALLER"] = { "Intellect", "Stamina" },
  ["SUNCLERIC"] = { "Intellect", "Strength", "Stamina" },
  ["TINKER"] = { "Agility", "Intellect" },
  ["PROPHET"] = { "Intellect", "Stamina" },
  ["REAPER"] = { "Strength", "Stamina" },
  ["WILDWALKER"] = { "Strength", "Intellect", "Stamina" },
  ["SPIRITMAGE"] = { "Agility", "Spirit" },
}

-- Neutral stat names in the data above -> this addon's stat keys.
local STAT_KEYS = {
	Agility = "AGILITY", Strength = "STRENGTH", Intellect = "INTELLECT", Spirit = "SPIRIT",
	Stamina = "STAMINA", AttackPower = "ATTACK_POWER", RangedAttackPower = "RANGED_ATTACK_POWER",
	SpellPower = "SPELL_POWER", CritRating = "CRIT", HitRating = "HIT", HasteRating = "HASTE",
	ArmorPenetration = "ARMOR_PENETRATION", Armor = "ARMOR", Dodge = "DODGE", Parry = "PARRY",
	Defense = "DEFENSE_SKILL", Mp5 = "MANA_REGENERATION",
}

-- The source weights carry no weapon DPS value. Weapon-based roles get one so weapon swaps
-- are judged on damage too; the size is in line with this addon's WotLK physical specs.
local WEAPON_DPS_BY_ROLE = { MELEE = 3, RANGED = 3, TANK = 1 }

-- Usability is decided from the character's own armor/weapon skills (see
-- class_can_use_standard_family in Item-ItemScore.lua), so every family is allowed here.
local ALL_ITEMTYPES = { CLOTH=1, LEATHER=1, MAIL=1, PLATE=1, SHIELD=1, BOW=1, CROSSBOW=1, DAGGER=1, FIST=1, GUN=1,
	MACE=1, TH_MACE=1, TH_POLE=1, TH_STAFF=1, SWORD=1, TH_SWORD=1, AXE=1, TH_AXE=1, WAND=1, THROWN=1, OFFHAND=1,
	MISCARM=1, JEWELERY=1 }

ItemScore.CoAClassSpecs = CoAClassSpec
ItemScore.CoAClassPrimaryStats = CoAClassPrimaryStats

local function BuildRule(spec)
	local stats = {}
	for neutral, weight in pairs(spec.weights or {}) do
		local key = STAT_KEYS[neutral]
		if key then stats[key] = weight end
	end
	local dps = 0
	for _, role in ipairs(spec.roles or {}) do dps = math.max(dps, WEAPON_DPS_BY_ROLE[role] or 0) end
	if dps > 0 then stats.DAMAGE_PER_SECOND = dps end
	stats.STAMINA = stats.STAMINA or 0.001 -- tie-breaker, as the stock builds do
	local itemtypes = {}
	for k, v in pairs(ALL_ITEMTYPES) do itemtypes[k] = v end
	return { name = spec.name, itemtypes = itemtypes, stats = stats, caps = {} }
end

-- Replace the generic CUSTOM builds with the player's CoA class specs. Safe to call again.
function ItemScore:ApplyCoAClassRules()
	if self.CoAClass then return true end
	local className, token = UnitClass("player")
	local data = token and CoAClassSpec[token]
	if not data or (self.rules[token] and token ~= "CUSTOM") then return false end

	local rules, names, sources = {}, {}, {}
	for i, spec in ipairs(data.specs) do
		rules[i] = BuildRule(spec)
		names[i] = spec.name
		sources[i] = { label = ("Conquest of Azeroth %s %s (coa-db class_spec_meta)"):format(data.name, spec.name), mode = "coa_class_spec" }
	end
	self.rules.CUSTOM = rules
	if self.RuleSources then self.RuleSources.CUSTOM = sources end
	if ZGV.SpecByNumber then ZGV.SpecByNumber.CUSTOM = names end
	self.CoAClass = { token = token, name = data.name or className, specs = data.specs }
	if self.Builds and self.SetData then self:SetData() end -- refresh build names if already built
	return true
end

-- The spec to start from: the first one built on the character's chosen primary stat.
function ItemScore:GetCoADefaultBuild()
	local coa = self.CoAClass
	if not coa then return 1 end
	local chosen
	if C_PrimaryStat and C_PrimaryStat.GetActivePrimaryStat then
		local ok, stat = pcall(C_PrimaryStat.GetActivePrimaryStat, C_PrimaryStat)
		if ok and stat then
			local ok2, _, _, _, name = pcall(C_PrimaryStat.GetPrimaryStatInfo, C_PrimaryStat, stat)
			if ok2 and type(name) == "string" then chosen = name:lower() end
		end
	end
	if chosen then
		for i, spec in ipairs(coa.specs) do
			if spec.primaryStat and spec.primaryStat:lower() == chosen then return i end
		end
	end
	return 1
end

-- Spec for /zdps, /ztank and /zheal, preferring one built on the chosen primary stat.
local ROLE_MATCH = {
	tank = { TANK = true },
	heal = { HEALER = true, SUPPORT = true },
	dps = { MELEE = true, RANGED = true, CASTER = true },
}
function ItemScore:GetCoARoleBuild(role)
	local coa, wanted = self.CoAClass, ROLE_MATCH[role]
	if not coa or not wanted then return nil end
	local preferred, first = self:GetCoADefaultBuild(), nil
	for i, spec in ipairs(coa.specs) do
		for _, r in ipairs(spec.roles or {}) do
			if wanted[r] then
				if i == preferred then return i end
				first = first or i
			end
		end
	end
	return first
end

ItemScore:ApplyCoAClassRules()
